spring:
  config:
    import: "optional:configserver:instead"
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
---
management:
  zipkin:
    tracing:
      endpoint: http://fec-bpm-alb-278312111.ap-southeast-1.elb.amazonaws.com:9411/api/v2/spans