server:
  port: 8081
---
spring:
  application:
    name: gateway-service
  profiles:
    active: ${PROFILE_ACTIVE:local}
---
security:
  public-key: -----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuakHBgwiKwyK3tb2XvLD wpcLFuxQTz8/2Ti4wsBngb58CGwpXCD2TRFmI2ISDsP25qifO7vvzdmPjvQwg8DM Wr4hcNAhmuaYNeu6FY+T4NVdlk2zte9BPyU2YMjB6j+YjaKsrjH56RV4eOQoosRa 8z9Ez9nT4NblcNyAiHH2BN72ClWx1EcCuJ2AO1qysUfNJrPeLv6BJQSQ3J/+86wq DFfJh2Fe2J7m7cQPkCs3IKDbbDrZQOiuIw6wicVdSbDRwdbapBul98t927hLzoFd GCHlfGgoExKjVH+pc+JK4ZZ3e987AuJcs7Ka4GCvb/kzNcnb4fIlhXXa/lV21t8S lwIDAQAB -----END PUBLIC KEY-----
  service-key: 11ecde83-1597-454b-91c6-db37b4dc1156
---
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints (e.g., health, metrics, etc.)
  endpoint:
    health:
      show-details: always # Show detailed health information
  metrics:
    tags:
      application: gateway-service
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3 # Use B3 propagation for distributed tracing
    enabled: true
---
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /authentication/v3/api-docs
        name: AUTHENTICATION-SERVICE
        display-name: Authentication Service Document Api

      - url: /document/v3/api-docs
        name: DOCUMENT-SERVICE
        display-name: Document Service Document Api

      - url: /management/v3/api-docs
        name: BOT-MANAGEMENT-SERVICE
        display-name: Bot Management Service Document Api