spring:
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: "optional:configserver:instead"
---
gateway:
  routes:
    authentication-service: http://localhost:8092
---
management:
  zipkin:
    tracing:
      endpoint: http://fec-bpm-alb-278312111.ap-southeast-1.elb.amazonaws.com:9411/api/v2/spans